### PR TITLE
Add events for claims and payments

### PR DESCRIPTION
**Pull request by sonnyandersson1**
Events added: 
- begin_claim_recording
- honor_pledge_confirmed
- playback_claim_recording
- redo_claim_recording
- stop_claim_recording
- submit_claim_recording
- home_payment_card_click
- payment_connected

### CODE REVIEW

**Comment by sampettersson** [comment]
@sonnyandersson1 i redid the events for recording, to change the terminology from claim to embark recording (as the recorder is generic to embark, we could end up using for something else in the future) does that look ok? We could deduce that it is in fact from a claims flow by checking the storyName if that is needed in the future.

**Comment by sonnyandersson1** [comment]
I understand! It looks good with your suggestions :))

**Comment by sampettersson** [comment]
Then lets merge this 🎉

**Comment by sampettersson** [comment]
I'll create tickets to add these events to the apps

**Pull request merged**
