### PR TITLE
Notification events

### PR DESCRIPTION
**Pull request by sampettersson**
Add events for push notifications, suggestion is to always send `granted: true` on android on app boot and on iOS we actually fetch the status on boot and set the boolean accordingly.

### CODE REVIEW

**Review by hugokallstrom — COMMENTED** [review]
We should be able to check notification permission on boot as well, right @hedvigoscar ?

**Comment by hedvigoscar** [comment]
I believe so, yes.

It will probably only become relevant in SDK 33 (android 13), but there will be a future distinction here.

**Comment by hedvigoscar** [comment]
It's probably also possible to check this once we receive a notification payload, and set it at that point, given that the setting can change during the lifetime of the application execution.

**Review by hedvigoscar — APPROVED** [review]
lgtm!

**Pull request merged**
